---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/profifet/repositories/profifet/index.html
    - /bin/rm -rf $DEPLOY_PATH/*
    - npm install
    - npm run build
    - cp -r dist/* $DEPLOY_PATH
