---
deployment:
  tasks:
    - echo "📦 Установка зависимостей..."
    - /usr/local/bin/npm install

    - echo "🛠️ Сборка проекта..."
    - /usr/local/bin/npm run build

    - echo "🧹 Очистка старой версии сайта..."
    - /bin/rm -rf /home/profifet/public_html/*

    - echo "📁 Копирование новой версии сайта..."
    - /bin/cp -r dist/* /home/profifet/public_html/

    - echo "✅ Деплой завершён успешно."
